### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by davidhan527** [honeybadger-io/honeybadger-rails-webpacker-example#31]
I'm trying to follow the example in environment.js in my rails 6 application. 

I'm not sure if it's because the rails version is different, but this example is not working for my project.
Do you have an example of how I can upload sourcemaps for my rails 6 project or have any idea what might be the issue here?

This is the error I'm getting

```
config/webpack/environment.js:10
environment.plugins.set(
                    ^

TypeError: environment.plugins.set is not a function
    at Object.<anonymous> (config/webpack/environment.js:10:21)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (config/webpack/development.js:3:21)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
npm ERR! code 1
```

**Comment by joshuap** [comment]
@davidhan527 sorry for not getting back to you on this. I'm going to be archiving this repo since it tends to go out of date; we'll make up for it by providing better documentation. :) In any case, you can find a Rails/webpacker examples here:

https://github.com/honeybadger-io/honeybadger-webpack#rails-webpacker-configwebpackenvironmentjs

That example uses `append` instead of `set`—perhaps that's something? In any case, if you have trouble with the webpack plugin in the  future, feel free to create an issue [here](https://github.com/honeybadger-io/honeybadger-webpack/issues) or email support at honeybadger.io.
